function Equation1(Phi,PhiZ,PhiZZ, S,SZ,SZZ, Sdot,SdotZ,SdotZZ, Phidot,PhidotZ,PhidotZZ, A,AZ,AZZ, z,LN, X)

eq = (-2*Power(M,4))/9. + 4*M*Phi + 12*S + (4*M*PhiZ*z)/3. + 8*SZ*z + (10*Power(M,4)*X*z)/9. - 4*M*Phi*X*z + (8*Power(M,2)*Power(X,3)*z)/3. - (4*Power(M,3)*Phi*Power(z,2))/3. + 6*Power(Phi,2)*Power(z,2) + (2*Power(M,2)*S*Power(z,2))/3. + SZZ*Power(z,2) - (4*M*PhiZ*X*Power(z,2))/3. - (16*Power(M,4)*Power(X,2)*Power(z,2))/9. - 8*M*Phi*Power(X,2)*Power(z,2) - (4*Power(M,3)*PhiZ*Power(z,3))/9. + 4*Phi*PhiZ*Power(z,3) + 4*Power(M,3)*Phi*X*Power(z,3) + 6*Power(Phi,2)*X*Power(z,3) - (8*Power(M,2)*S*X*Power(z,3))/3. - (8*M*PhiZ*Power(X,2)*Power(z,3))/3. + (8*Power(M,4)*Power(X,3)*Power(z,3))/9. - 2*Power(M,2)*Power(Phi,2)*Power(z,4) + (2*Power(PhiZ,2)*Power(z,4))/3. + 4*M*Phi*S*Power(z,4) + (4*Power(M,3)*PhiZ*X*Power(z,4))/3. + 4*Phi*PhiZ*X*Power(z,4) - (8*Power(M,3)*Phi*Power(X,2)*Power(z,4))/3. + (8*Power(M,2)*S*Power(X,2)*Power(z,4))/3. - (4*Power(M,2)*Phi*PhiZ*Power(z,5))/3. + (4*M*PhiZ*S*Power(z,5))/3. + 2*Power(M,2)*Power(Phi,2)*X*Power(z,5) + (2*Power(PhiZ,2)*X*Power(z,5))/3. - 8*M*Phi*S*X*Power(z,5) - (8*Power(M,3)*PhiZ*Power(X,2)*Power(z,5))/9. - (2*Power(M,2)*Power(PhiZ,2)*Power(z,6))/9. + 6*Power(Phi,2)*S*Power(z,6) + (4*Power(M,2)*Phi*PhiZ*X*Power(z,6))/3. - (8*M*PhiZ*S*X*Power(z,6))/3. + 4*Phi*PhiZ*S*Power(z,7) + (2*Power(M,2)*Power(PhiZ,2)*X*Power(z,7))/9. + (2*Power(PhiZ,2)*S*Power(z,8))/3.; 

return(eq);
end;

function Equation2(Phi,PhiZ,PhiZZ, S,SZ,SZZ, Sdot,SdotZ,SdotZZ, Phidot,PhidotZ,PhidotZZ, A,AZ,AZZ, z,LN, X)

eq = -2*Sdot + Power(z,-4) + X/Power(z,3) - SdotZ*z - Power(M,4)/(3. *(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)))) - (9*S)/(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2))) + (6*Sdot)/(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2))) - (3*Power(M,2)*Power(X,2))/(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2))) + 3/(Power(z,4)*(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)))) + (6*X)/(Power(z,3)*(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)))) + (3*Power(X,2))/(Power(z,2)*(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)))) - (3*SZ*z)/(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2))) + (2*Power(M,4)*X*z)/(3. *(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)))) - (18*S*X*z)/(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2))) - (2*Power(M,2)*Power(X,3)*z)/(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2))) + (3*Power(M,2)*S*Power(z,2))/(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2))) + (2*Power(M,2)*Sdot*Power(z,2))/(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2))) - (6*SZ*X*Power(z,2))/(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2))) - (9*S*Power(X,2)*Power(z,2))/(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2))) + (Power(M,2)*SZ*Power(z,3))/(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2))) - (4*Power(M,2)*Sdot*X*Power(z,3))/(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2))) - (3*SZ*Power(X,2)*Power(z,3))/(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2))) - (18*S*Sdot*Power(z,4))/(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2))) - (6*Sdot*SZ*Power(z,5))/(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2))) + (2*S*Vfun(z*(M - M*X*z + Phi*Power(z,2))))/3. + (2*Vfun(z*(M - M*X*z + Phi*Power(z,2))))/(3. *Power(z,4)) + (2*X*Vfun(z*(M - M*X*z + Phi*Power(z,2))))/(3. *Power(z,3)) - (2*Power(M,2)*Vfun(z*(M - M*X*z + Phi*Power(z,2))))/(9. *Power(z,2)) + (2*Power(M,2)*X*Vfun(z*(M - M*X*z + Phi*Power(z,2))))/(9. *z); 

return(eq);
end;

function Equation3(Phi,PhiZ,PhiZZ, S,SZ,SZZ, Sdot,SdotZ,SdotZZ, Phidot,PhidotZ,PhidotZZ, A,AZ,AZZ, z,LN, X)

eq = -2*Phidot*Power(z,3) - PhidotZ*Power(z,4) - (9*M*z)/(2. *(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)))) - (27*Phi*Power(z,3))/(4. *(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)))) + (9*Phidot*Power(z,3))/(2. *(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)))) + (27*M*Power(X,2)*Power(z,3))/(4. *(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)))) - (9*PhiZ*Power(z,4))/(4. *(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)))) - (27*Phi*X*Power(z,4))/(2. *(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)))) + (9*M*Power(X,3)*Power(z,4))/(2. *(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)))) + (9*Power(M,2)*Phi*Power(z,5))/(4. *(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)))) + (3*Power(M,2)*Phidot*Power(z,5))/(2. *(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)))) + (27*M*S*Power(z,5))/(4. *(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)))) - (9*M*Sdot*Power(z,5))/(2. *(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)))) - (9*PhiZ*X*Power(z,5))/(2. *(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)))) - (27*Phi*Power(X,2)*Power(z,5))/(4. *(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)))) + (3*Power(M,2)*PhiZ*Power(z,6))/(4. *(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)))) + (9*M*SZ*Power(z,6))/(4. *(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)))) - (3*Power(M,2)*Phidot*X*Power(z,6))/(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2))) + (9*M*Sdot*X*Power(z,6))/(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2))) - (9*PhiZ*Power(X,2)*Power(z,6))/(4. *(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)))) - (27*Phidot*S*Power(z,7))/(2. *(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)))) - (27*Phi*Sdot*Power(z,7))/(2. *(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)))) - (9*PhiZ*Sdot*Power(z,8))/(2. *(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)))) - (9*Phidot*SZ*Power(z,8))/(2. *(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)))) - DV(z*(M - M*X*z + Phi*Power(z,2)))/2.; 

return(eq);
end;

function Equation4(Phi,PhiZ,PhiZZ, S,SZ,SZZ, Sdot,SdotZ,SdotZZ, Phidot,PhidotZ,PhidotZZ, A,AZ,AZZ, z,LN, X)

eq = 2 + 2*Power(M,2)*Power(z,2) - 4*Power(M,2)*X*Power(z,3) + 6*A*Power(z,4) + 6*M*Phi*Power(z,4) - 4*M*Phidot*Power(z,4) + 6*AZ*Power(z,5) + 2*M*PhiZ*Power(z,5) + 8*M*Phidot*X*Power(z,5) + AZZ*Power(z,6) - 12*Phi*Phidot*Power(z,6) - 4*Phidot*PhiZ*Power(z,7) - 54/Power(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)),2) - (108*X*z)/Power(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)),2) - (54*Power(X,2)*Power(z,2))/Power(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)),2) + (6*Power(M,4)*Power(z,4))/Power(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)),2) + (162*S*Power(z,4))/Power(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)),2) - (108*Sdot*Power(z,4))/Power(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)),2) + (54*Power(M,2)*Power(X,2)*Power(z,4))/Power(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)),2) + (54*SZ*Power(z,5))/Power(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)),2) - (12*Power(M,4)*X*Power(z,5))/Power(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)),2) + (324*S*X*Power(z,5))/Power(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)),2) + (36*Power(M,2)*Power(X,3)*Power(z,5))/Power(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)),2) - (54*Power(M,2)*S*Power(z,6))/Power(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)),2) - (36*Power(M,2)*Sdot*Power(z,6))/Power(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)),2) + (108*SZ*X*Power(z,6))/Power(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)),2) + (162*S*Power(X,2)*Power(z,6))/Power(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)),2) - (18*Power(M,2)*SZ*Power(z,7))/Power(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)),2) + (72*Power(M,2)*Sdot*X*Power(z,7))/Power(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)),2) + (54*SZ*Power(X,2)*Power(z,7))/Power(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)),2) + (324*S*Sdot*Power(z,8))/Power(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)),2) + (108*Sdot*SZ*Power(z,9))/Power(3 - Power(M,2)*Power(z,2) + 3*S*Power(z,4) + X*z*(3 + Power(M,2)*Power(z,2)),2) - (4*Vfun(z*(M - M*X*z + Phi*Power(z,2))))/3.; 

return(eq);
end;

